### ISSUE TITLE
Cannot install nor delete Redis-Stack-Server on M2 Pro

### ISSUE THREAD

**Issue by mmangione** [redis-stack/homebrew-redis-stack#44]
Here redis stack server seems to be broken on Apple Silicon. Here is the issue I get when it fails to verify, then attempts to uninstall.

```
➜  bin git:(stable) brew install redis-stack-server
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Downloading https://redismodules.s3.amazonaws.com/redis-stack/redis-stack-se
Already downloaded: /Users/mmangione/Library/Caches/Homebrew/downloads/233de96d05b20119de565d70e00318af8e5a7cac497d6248137041730192055e--redis-stack-server-7.2.0-v10.monterey.arm64.zip
Warning: Cannot verify integrity of '233de96d05b20119de565d70e00318af8e5a7cac497d6248137041730192055e--redis-stack-server-7.2.0-v10.monterey.arm64.zip'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "bdd8ecb61f3619f898842d141d558b8c683767edce9874fd618a79a28cf68d64"
All dependencies satisfied.
==> Installing Cask redis-stack-server
==> Purging files for version 7.2.0-v10 of Cask redis-stack-server
Error: undefined method `exists?' for class Dir
/opt/homebrew/Library/Taps/redis-stack/homebrew-redis-stack/Casks/redis-stack-server.rb:59:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:26:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/redis-stack/homebrew-redis-stack/issues/new
```

**Comment by Zer0-Tolerance** [comment]
same issue on my Mac
