### ISSUE TITLE
Error: undefined method `exists?' for class Dir for brew install --cask redis-stack

### ISSUE THREAD

**Issue by Devrath27** [redis-stack/homebrew-redis-stack#50]
CMD: **brew install --cask redis-stack**

Error: undefined method `exists?' for class Dir
/opt/homebrew/Library/Taps/redis-stack/homebrew-redis-stack/Casks/redis-stack-server.rb:59:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:26:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cask/installer.rb:360:in `block in satisfy_cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:346:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:346:in `satisfy_cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'

**Comment by yeroshalmimLF** [comment]
I am getting the same error. Someone Please Help!

**Comment by rtarway** [comment]
I am getting this error as well

**Comment by john-ju** [comment]
found a fix in an older issue

https://github.com/redis-stack/homebrew-redis-stack/issues/45#issuecomment-2148449328
