### ISSUE TITLE
Error: undefined method `exists?' for class Dir shows up when I brew install redis-stack

### ISSUE THREAD

**Issue by rtarway** [redis-stack/homebrew-redis-stack#52]
==> Installing Cask redis-stack-server
==> Purging files for version 7.2.0-v10 of Cask redis-stack-server
Error: undefined method `exists?' for class Dir
/usr/local/Homebrew/Library/Taps/redis-stack/homebrew-redis-stack/Casks/redis-stack-server.rb:59:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:26:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:360:in `block in satisfy_cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:346:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:346:in `satisfy_cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/redis-stack/homebrew-redis-stack/issues/new

HDGhsdjahgdh ~ % brew doctor
Your system is ready to brew.

sdkfhskdjfskdhf ~ % brew config
HOMEBREW_VERSION: 4.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fdb0d53990d3e62e25325a6f89dbb769e84a530
Last commit: 4 days ago
Core tap JSON: 31 May 01:44 UTC
Core cask tap JSON: 31 May 01:44 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.1 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3

**Comment by john-ju** [comment]
found a fix in an older issue

https://github.com/redis-stack/homebrew-redis-stack/issues/45#issuecomment-2148449328
