### ISSUE TITLE
undefined method `exists`? for class Dir

### ISSUE THREAD

**Issue by harunkelesoglu** [redis-stack/homebrew-redis-stack#53]
When i tried install redis stack using brew i encountered the following errror:
```shell
Harun-MacBook-Pro:Projects harunkelesoglu$ brew install redis-stack
==> Downloading https://redismodules.s3.amazonaws.com/redis-stack/.donotremove
-#O=-#     #        #                                                                                                                                                                                                 
==> Installing dependencies: libomp, redis-stack-server, redis-stack-redisinsight
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/manifests/18.1.6
############################################################################################################################################################################################################### 100.0%
==> Fetching libomp
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/blobs/sha256:a70d0d40688e8aff2129836f502b2b405b41113cab3ebb0c46c5a3ed049513b1
############################################################################################################################################################################################################### 100.0%
==> Installing libomp
==> Pouring libomp--18.1.6.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libomp/18.1.6: 9 files, 1.7MB
==> Downloading https://redismodules.s3.amazonaws.com/redis-stack/redis-stack-server-7.2.0-v10.monterey.arm64.zip
############################################################################################################################################################################################################### 100.0%
Warning: Cannot verify integrity of '233de96d05b20119de565d70e00318af8e5a7cac497d6248137041730192055e--redis-stack-server-7.2.0-v10.monterey.arm64.zip'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "bdd8ecb61f3619f898842d141d558b8c683767edce9874fd618a79a28cf68d64"
==> Installing Cask redis-stack-server
==> Purging files for version 7.2.0-v10 of Cask redis-stack-server
Error: undefined method `exists?' for class Dir
/opt/homebrew/Library/Taps/redis-stack/homebrew-redis-stack/Casks/redis-stack-server.rb:59:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:26:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cask/installer.rb:360:in `block in satisfy_cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:346:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:346:in `satisfy_cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

**Comment by john-ju** [comment]
found a fix in an older issue

https://github.com/redis-stack/homebrew-redis-stack/issues/45#issuecomment-2148449328
