### ISSUE TITLE
Error: redis-stack/redis-stack/redis-stack-server: undefined method `exists?' for class File

### ISSUE THREAD

**Issue by aselder** [redis-stack/homebrew-redis-stack#57]
```
==> Purging files for version 7.2.0-v11 of Cask redis-stack-server
Error: redis-stack/redis-stack/redis-stack-server: undefined method `exists?' for class File
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405001954.235/Casks/redis-stack-server.rb:34:in `block (3 levels) in load'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405001954.235/Casks/redis-stack-server.rb:32:in `each'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405001954.235/Casks/redis-stack-server.rb:32:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:30:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:474:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:471:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:430:in `start_upgrade'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:195:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

**Comment by dstanley-ttech** [comment]
I resolved this on my machine by editing the /opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240405001954.235/Casks/redis-stack-server.rb file, with the same edits as a recent commit to the cask seen here: https://github.com/redis-stack/homebrew-redis-stack/commit/c31dd8db426777dfeceec2b3f1fd7403df6c0250

Specifically I edited line 34 to change `if File.exists?(dest)` to `if File.exist?(dest)`
